// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package eds

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatEdsArtifact is an auto-generated flat version of EdsArtifact.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatEdsArtifact struct {
	ImageName        *string `mapstructure:"image_name" required:"true" cty:"image_name" hcl:"image_name"`
	ImageDescription *string `mapstructure:"description" required:"false" cty:"description" hcl:"description"`
}

// FlatMapstructure returns a new FlatEdsArtifact.
// FlatEdsArtifact is an auto-generated flat version of EdsArtifact.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*EdsArtifact) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatEdsArtifact)
}

// HCL2Spec returns the hcl spec of a EdsArtifact.
// This spec is used by HCL to read the fields of EdsArtifact.
// The decoded values from this spec will then be applied to a FlatEdsArtifact.
func (*FlatEdsArtifact) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"image_name":  &hcldec.AttrSpec{Name: "image_name", Type: cty.String, Required: false},
		"description": &hcldec.AttrSpec{Name: "description", Type: cty.String, Required: false},
	}
	return s
}

// FlatEdsComputerTemplate is an auto-generated flat version of EdsComputerTemplate.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatEdsComputerTemplate struct {
	Id                       *string             `mapstructure:"id" required:"false" cty:"id" hcl:"id"`
	Name                     *string             `mapstructure:"name" required:"false" cty:"name" hcl:"name"`
	Description              *string             `mapstructure:"description" required:"false" cty:"description" hcl:"description"`
	SourceImageFilter        *FlatEdsImageFilter `mapstructure:"source_image_filter" required:"false" cty:"source_image_filter" hcl:"source_image_filter"`
	InstanceType             *string             `mapstructure:"instance_type" required:"true" cty:"instance_type" hcl:"instance_type"`
	RootDiskSizeGib          *int                `mapstructure:"root_disk_size_gib" required:"true" cty:"root_disk_size_gib" hcl:"root_disk_size_gib"`
	RootDiskPerformanceLevel *string             `mapstructure:"root_disk_performance_level" required:"false" cty:"root_disk_performance_level" hcl:"root_disk_performance_level"`
	UserDiskSizeGib          []int32             `mapstructure:"user_disk_size_gib" required:"false" cty:"user_disk_size_gib" hcl:"user_disk_size_gib"`
	UserDiskPerformanceLevel *string             `mapstructure:"user_disk_performance_level" required:"false" cty:"user_disk_performance_level" hcl:"user_disk_performance_level"`
	Language                 *string             `mapstructure:"language" required:"false" cty:"language" hcl:"language"`
}

// FlatMapstructure returns a new FlatEdsComputerTemplate.
// FlatEdsComputerTemplate is an auto-generated flat version of EdsComputerTemplate.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*EdsComputerTemplate) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatEdsComputerTemplate)
}

// HCL2Spec returns the hcl spec of a EdsComputerTemplate.
// This spec is used by HCL to read the fields of EdsComputerTemplate.
// The decoded values from this spec will then be applied to a FlatEdsComputerTemplate.
func (*FlatEdsComputerTemplate) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"id":                          &hcldec.AttrSpec{Name: "id", Type: cty.String, Required: false},
		"name":                        &hcldec.AttrSpec{Name: "name", Type: cty.String, Required: false},
		"description":                 &hcldec.AttrSpec{Name: "description", Type: cty.String, Required: false},
		"source_image_filter":         &hcldec.BlockSpec{TypeName: "source_image_filter", Nested: hcldec.ObjectSpec((*FlatEdsImageFilter)(nil).HCL2Spec())},
		"instance_type":               &hcldec.AttrSpec{Name: "instance_type", Type: cty.String, Required: false},
		"root_disk_size_gib":          &hcldec.AttrSpec{Name: "root_disk_size_gib", Type: cty.Number, Required: false},
		"root_disk_performance_level": &hcldec.AttrSpec{Name: "root_disk_performance_level", Type: cty.String, Required: false},
		"user_disk_size_gib":          &hcldec.AttrSpec{Name: "user_disk_size_gib", Type: cty.List(cty.Number), Required: false},
		"user_disk_performance_level": &hcldec.AttrSpec{Name: "user_disk_performance_level", Type: cty.String, Required: false},
		"language":                    &hcldec.AttrSpec{Name: "language", Type: cty.String, Required: false},
	}
	return s
}

// FlatEdsImageFilter is an auto-generated flat version of EdsImageFilter.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatEdsImageFilter struct {
	ImageId          *string `mapstructure:"image_id" required:"false" cty:"image_id" hcl:"image_id"`
	ImageName        *string `mapstructure:"image_name" required:"false" cty:"image_name" hcl:"image_name"`
	ImageVersion     *string `mapstructure:"image_version" required:"false" cty:"image_version" hcl:"image_version"`
	ImageType        *string `mapstructure:"image_type" required:"false" cty:"image_type" hcl:"image_type"`
	ImageStatus      *string `mapstructure:"image_status" required:"false" cty:"image_status" hcl:"image_status"`
	ProtocolType     *string `mapstructure:"protocol_type" required:"false" cty:"protocol_type" hcl:"protocol_type"`
	InstanceType     *string `mapstructure:"desktop_instance_type" required:"false" cty:"desktop_instance_type" hcl:"desktop_instance_type"`
	SessionType      *string `mapstructure:"session_type" required:"false" cty:"session_type" hcl:"session_type"`
	GpuCategory      *bool   `mapstructure:"gpu_category" required:"false" cty:"gpu_category" hcl:"gpu_category"`
	GpuDriverVersion *string `mapstructure:"gpu_driver_version" required:"false" cty:"gpu_driver_version" hcl:"gpu_driver_version"`
	OsType           *string `mapstructure:"os_type" required:"false" cty:"os_type" hcl:"os_type"`
	OsLanguageType   *string `mapstructure:"language_type" required:"false" cty:"language_type" hcl:"language_type"`
}

// FlatMapstructure returns a new FlatEdsImageFilter.
// FlatEdsImageFilter is an auto-generated flat version of EdsImageFilter.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*EdsImageFilter) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatEdsImageFilter)
}

// HCL2Spec returns the hcl spec of a EdsImageFilter.
// This spec is used by HCL to read the fields of EdsImageFilter.
// The decoded values from this spec will then be applied to a FlatEdsImageFilter.
func (*FlatEdsImageFilter) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"image_id":              &hcldec.AttrSpec{Name: "image_id", Type: cty.String, Required: false},
		"image_name":            &hcldec.AttrSpec{Name: "image_name", Type: cty.String, Required: false},
		"image_version":         &hcldec.AttrSpec{Name: "image_version", Type: cty.String, Required: false},
		"image_type":            &hcldec.AttrSpec{Name: "image_type", Type: cty.String, Required: false},
		"image_status":          &hcldec.AttrSpec{Name: "image_status", Type: cty.String, Required: false},
		"protocol_type":         &hcldec.AttrSpec{Name: "protocol_type", Type: cty.String, Required: false},
		"desktop_instance_type": &hcldec.AttrSpec{Name: "desktop_instance_type", Type: cty.String, Required: false},
		"session_type":          &hcldec.AttrSpec{Name: "session_type", Type: cty.String, Required: false},
		"gpu_category":          &hcldec.AttrSpec{Name: "gpu_category", Type: cty.Bool, Required: false},
		"gpu_driver_version":    &hcldec.AttrSpec{Name: "gpu_driver_version", Type: cty.String, Required: false},
		"os_type":               &hcldec.AttrSpec{Name: "os_type", Type: cty.String, Required: false},
		"language_type":         &hcldec.AttrSpec{Name: "language_type", Type: cty.String, Required: false},
	}
	return s
}

// FlatEdsOfficeSite is an auto-generated flat version of EdsOfficeSite.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatEdsOfficeSite struct {
	Id             *string                          `mapstructure:"id" required:"false" cty:"id" hcl:"id"`
	Name           *string                          `mapstructure:"name" required:"false" cty:"name" hcl:"name"`
	CidrBlock      *string                          `mapstructure:"cidr_block" required:"false" cty:"cidr_block" hcl:"cidr_block"`
	InternetAccess *FlatEdsOfficeSiteInternetAccess `mapstructure:"internet_access" required:"false" cty:"internet_access" hcl:"internet_access"`
	Cen            *FlatEdsOfficeSiteCen            `mapstructure:"cen" required:"false" cty:"cen" hcl:"cen"`
}

// FlatMapstructure returns a new FlatEdsOfficeSite.
// FlatEdsOfficeSite is an auto-generated flat version of EdsOfficeSite.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*EdsOfficeSite) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatEdsOfficeSite)
}

// HCL2Spec returns the hcl spec of a EdsOfficeSite.
// This spec is used by HCL to read the fields of EdsOfficeSite.
// The decoded values from this spec will then be applied to a FlatEdsOfficeSite.
func (*FlatEdsOfficeSite) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"id":              &hcldec.AttrSpec{Name: "id", Type: cty.String, Required: false},
		"name":            &hcldec.AttrSpec{Name: "name", Type: cty.String, Required: false},
		"cidr_block":      &hcldec.AttrSpec{Name: "cidr_block", Type: cty.String, Required: false},
		"internet_access": &hcldec.BlockSpec{TypeName: "internet_access", Nested: hcldec.ObjectSpec((*FlatEdsOfficeSiteInternetAccess)(nil).HCL2Spec())},
		"cen":             &hcldec.BlockSpec{TypeName: "cen", Nested: hcldec.ObjectSpec((*FlatEdsOfficeSiteCen)(nil).HCL2Spec())},
	}
	return s
}

// FlatEdsOfficeSiteCen is an auto-generated flat version of EdsOfficeSiteCen.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatEdsOfficeSiteCen struct {
	Id         *string `mapstructure:"id" required:"false" cty:"id" hcl:"id"`
	OwnerId    *int64  `mapstructure:"owner_id" required:"false" cty:"owner_id" hcl:"owner_id"`
	VerifyCode *string `mapstructure:"verify_code" required:"false" cty:"verify_code" hcl:"verify_code"`
}

// FlatMapstructure returns a new FlatEdsOfficeSiteCen.
// FlatEdsOfficeSiteCen is an auto-generated flat version of EdsOfficeSiteCen.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*EdsOfficeSiteCen) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatEdsOfficeSiteCen)
}

// HCL2Spec returns the hcl spec of a EdsOfficeSiteCen.
// This spec is used by HCL to read the fields of EdsOfficeSiteCen.
// The decoded values from this spec will then be applied to a FlatEdsOfficeSiteCen.
func (*FlatEdsOfficeSiteCen) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"id":          &hcldec.AttrSpec{Name: "id", Type: cty.String, Required: false},
		"owner_id":    &hcldec.AttrSpec{Name: "owner_id", Type: cty.Number, Required: false},
		"verify_code": &hcldec.AttrSpec{Name: "verify_code", Type: cty.String, Required: false},
	}
	return s
}

// FlatEdsOfficeSiteInternetAccess is an auto-generated flat version of EdsOfficeSiteInternetAccess.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatEdsOfficeSiteInternetAccess struct {
	Enabled   *bool  `mapstructure:"enabled" required:"false" cty:"enabled" hcl:"enabled"`
	Bandwidth *int32 `mapstructure:"bandwidth" required:"false" cty:"bandwidth" hcl:"bandwidth"`
}

// FlatMapstructure returns a new FlatEdsOfficeSiteInternetAccess.
// FlatEdsOfficeSiteInternetAccess is an auto-generated flat version of EdsOfficeSiteInternetAccess.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*EdsOfficeSiteInternetAccess) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatEdsOfficeSiteInternetAccess)
}

// HCL2Spec returns the hcl spec of a EdsOfficeSiteInternetAccess.
// This spec is used by HCL to read the fields of EdsOfficeSiteInternetAccess.
// The decoded values from this spec will then be applied to a FlatEdsOfficeSiteInternetAccess.
func (*FlatEdsOfficeSiteInternetAccess) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"enabled":   &hcldec.AttrSpec{Name: "enabled", Type: cty.Bool, Required: false},
		"bandwidth": &hcldec.AttrSpec{Name: "bandwidth", Type: cty.Number, Required: false},
	}
	return s
}

// FlatEdsPolicyGroup is an auto-generated flat version of EdsPolicyGroup.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatEdsPolicyGroup struct {
	Id   *string `mapstructure:"id" required:"false" cty:"id" hcl:"id"`
	Name *string `mapstructure:"name" required:"false" cty:"name" hcl:"name"`
}

// FlatMapstructure returns a new FlatEdsPolicyGroup.
// FlatEdsPolicyGroup is an auto-generated flat version of EdsPolicyGroup.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*EdsPolicyGroup) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatEdsPolicyGroup)
}

// HCL2Spec returns the hcl spec of a EdsPolicyGroup.
// This spec is used by HCL to read the fields of EdsPolicyGroup.
// The decoded values from this spec will then be applied to a FlatEdsPolicyGroup.
func (*FlatEdsPolicyGroup) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"id":   &hcldec.AttrSpec{Name: "id", Type: cty.String, Required: false},
		"name": &hcldec.AttrSpec{Name: "name", Type: cty.String, Required: false},
	}
	return s
}

// FlatEdsUser is an auto-generated flat version of EdsUser.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatEdsUser struct {
	Name         *string `mapstructure:"name" required:"true" cty:"name" hcl:"name"`
	Email        *string `mapstructure:"email" required:"true" cty:"email" hcl:"email"`
	Phone        *string `mapstructure:"phone" required:"false" cty:"phone" hcl:"phone"`
	OwnerType    *string `mapstructure:"owner_type" required:"false" cty:"owner_type" hcl:"owner_type"`
	OrgId        *string `mapstructure:"org_id" required:"false" cty:"org_id" hcl:"org_id"`
	Remark       *string `mapstructure:"remark" required:"false" cty:"remark" hcl:"remark"`
	RealNickName *string `mapstructure:"real_nick_name" required:"false" cty:"real_nick_name" hcl:"real_nick_name"`
}

// FlatMapstructure returns a new FlatEdsUser.
// FlatEdsUser is an auto-generated flat version of EdsUser.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*EdsUser) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatEdsUser)
}

// HCL2Spec returns the hcl spec of a EdsUser.
// This spec is used by HCL to read the fields of EdsUser.
// The decoded values from this spec will then be applied to a FlatEdsUser.
func (*FlatEdsUser) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"name":           &hcldec.AttrSpec{Name: "name", Type: cty.String, Required: false},
		"email":          &hcldec.AttrSpec{Name: "email", Type: cty.String, Required: false},
		"phone":          &hcldec.AttrSpec{Name: "phone", Type: cty.String, Required: false},
		"owner_type":     &hcldec.AttrSpec{Name: "owner_type", Type: cty.String, Required: false},
		"org_id":         &hcldec.AttrSpec{Name: "org_id", Type: cty.String, Required: false},
		"remark":         &hcldec.AttrSpec{Name: "remark", Type: cty.String, Required: false},
		"real_nick_name": &hcldec.AttrSpec{Name: "real_nick_name", Type: cty.String, Required: false},
	}
	return s
}

// FlatEdsUserCommand is an auto-generated flat version of EdsUserCommand.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatEdsUserCommand struct {
	Type      *string `mapstructure:"type" required:"true" cty:"type" hcl:"type"`
	Content   *string `mapstructure:"content" required:"true" cty:"content" hcl:"content"`
	Encoding  *string `mapstructure:"encoding" required:"true" cty:"encoding" hcl:"encoding"`
	EndUserId *string `mapstructure:"end_user_id" required:"false" cty:"end_user_id" hcl:"end_user_id"`
	Role      *string `mapstructure:"role" required:"false" cty:"role" hcl:"role"`
	Timeout   *uint64 `mapstructure:"timeout" required:"false" cty:"timeout" hcl:"timeout"`
}

// FlatMapstructure returns a new FlatEdsUserCommand.
// FlatEdsUserCommand is an auto-generated flat version of EdsUserCommand.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*EdsUserCommand) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatEdsUserCommand)
}

// HCL2Spec returns the hcl spec of a EdsUserCommand.
// This spec is used by HCL to read the fields of EdsUserCommand.
// The decoded values from this spec will then be applied to a FlatEdsUserCommand.
func (*FlatEdsUserCommand) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"type":        &hcldec.AttrSpec{Name: "type", Type: cty.String, Required: false},
		"content":     &hcldec.AttrSpec{Name: "content", Type: cty.String, Required: false},
		"encoding":    &hcldec.AttrSpec{Name: "encoding", Type: cty.String, Required: false},
		"end_user_id": &hcldec.AttrSpec{Name: "end_user_id", Type: cty.String, Required: false},
		"role":        &hcldec.AttrSpec{Name: "role", Type: cty.String, Required: false},
		"timeout":     &hcldec.AttrSpec{Name: "timeout", Type: cty.Number, Required: false},
	}
	return s
}

// FlatRunConfig is an auto-generated flat version of RunConfig.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatRunConfig struct {
	Type                      *string                  `mapstructure:"communicator" cty:"communicator" hcl:"communicator"`
	PauseBeforeConnect        *string                  `mapstructure:"pause_before_connecting" cty:"pause_before_connecting" hcl:"pause_before_connecting"`
	SSHHost                   *string                  `mapstructure:"ssh_host" cty:"ssh_host" hcl:"ssh_host"`
	SSHPort                   *int                     `mapstructure:"ssh_port" cty:"ssh_port" hcl:"ssh_port"`
	SSHUsername               *string                  `mapstructure:"ssh_username" cty:"ssh_username" hcl:"ssh_username"`
	SSHPassword               *string                  `mapstructure:"ssh_password" cty:"ssh_password" hcl:"ssh_password"`
	SSHKeyPairName            *string                  `mapstructure:"ssh_keypair_name" undocumented:"true" cty:"ssh_keypair_name" hcl:"ssh_keypair_name"`
	SSHTemporaryKeyPairName   *string                  `mapstructure:"temporary_key_pair_name" undocumented:"true" cty:"temporary_key_pair_name" hcl:"temporary_key_pair_name"`
	SSHTemporaryKeyPairType   *string                  `mapstructure:"temporary_key_pair_type" cty:"temporary_key_pair_type" hcl:"temporary_key_pair_type"`
	SSHTemporaryKeyPairBits   *int                     `mapstructure:"temporary_key_pair_bits" cty:"temporary_key_pair_bits" hcl:"temporary_key_pair_bits"`
	SSHCiphers                []string                 `mapstructure:"ssh_ciphers" cty:"ssh_ciphers" hcl:"ssh_ciphers"`
	SSHClearAuthorizedKeys    *bool                    `mapstructure:"ssh_clear_authorized_keys" cty:"ssh_clear_authorized_keys" hcl:"ssh_clear_authorized_keys"`
	SSHKEXAlgos               []string                 `mapstructure:"ssh_key_exchange_algorithms" cty:"ssh_key_exchange_algorithms" hcl:"ssh_key_exchange_algorithms"`
	SSHPrivateKeyFile         *string                  `mapstructure:"ssh_private_key_file" undocumented:"true" cty:"ssh_private_key_file" hcl:"ssh_private_key_file"`
	SSHCertificateFile        *string                  `mapstructure:"ssh_certificate_file" cty:"ssh_certificate_file" hcl:"ssh_certificate_file"`
	SSHPty                    *bool                    `mapstructure:"ssh_pty" cty:"ssh_pty" hcl:"ssh_pty"`
	SSHTimeout                *string                  `mapstructure:"ssh_timeout" cty:"ssh_timeout" hcl:"ssh_timeout"`
	SSHWaitTimeout            *string                  `mapstructure:"ssh_wait_timeout" undocumented:"true" cty:"ssh_wait_timeout" hcl:"ssh_wait_timeout"`
	SSHAgentAuth              *bool                    `mapstructure:"ssh_agent_auth" undocumented:"true" cty:"ssh_agent_auth" hcl:"ssh_agent_auth"`
	SSHDisableAgentForwarding *bool                    `mapstructure:"ssh_disable_agent_forwarding" cty:"ssh_disable_agent_forwarding" hcl:"ssh_disable_agent_forwarding"`
	SSHHandshakeAttempts      *int                     `mapstructure:"ssh_handshake_attempts" cty:"ssh_handshake_attempts" hcl:"ssh_handshake_attempts"`
	SSHBastionHost            *string                  `mapstructure:"ssh_bastion_host" cty:"ssh_bastion_host" hcl:"ssh_bastion_host"`
	SSHBastionPort            *int                     `mapstructure:"ssh_bastion_port" cty:"ssh_bastion_port" hcl:"ssh_bastion_port"`
	SSHBastionAgentAuth       *bool                    `mapstructure:"ssh_bastion_agent_auth" cty:"ssh_bastion_agent_auth" hcl:"ssh_bastion_agent_auth"`
	SSHBastionUsername        *string                  `mapstructure:"ssh_bastion_username" cty:"ssh_bastion_username" hcl:"ssh_bastion_username"`
	SSHBastionPassword        *string                  `mapstructure:"ssh_bastion_password" cty:"ssh_bastion_password" hcl:"ssh_bastion_password"`
	SSHBastionInteractive     *bool                    `mapstructure:"ssh_bastion_interactive" cty:"ssh_bastion_interactive" hcl:"ssh_bastion_interactive"`
	SSHBastionPrivateKeyFile  *string                  `mapstructure:"ssh_bastion_private_key_file" cty:"ssh_bastion_private_key_file" hcl:"ssh_bastion_private_key_file"`
	SSHBastionCertificateFile *string                  `mapstructure:"ssh_bastion_certificate_file" cty:"ssh_bastion_certificate_file" hcl:"ssh_bastion_certificate_file"`
	SSHFileTransferMethod     *string                  `mapstructure:"ssh_file_transfer_method" cty:"ssh_file_transfer_method" hcl:"ssh_file_transfer_method"`
	SSHProxyHost              *string                  `mapstructure:"ssh_proxy_host" cty:"ssh_proxy_host" hcl:"ssh_proxy_host"`
	SSHProxyPort              *int                     `mapstructure:"ssh_proxy_port" cty:"ssh_proxy_port" hcl:"ssh_proxy_port"`
	SSHProxyUsername          *string                  `mapstructure:"ssh_proxy_username" cty:"ssh_proxy_username" hcl:"ssh_proxy_username"`
	SSHProxyPassword          *string                  `mapstructure:"ssh_proxy_password" cty:"ssh_proxy_password" hcl:"ssh_proxy_password"`
	SSHKeepAliveInterval      *string                  `mapstructure:"ssh_keep_alive_interval" cty:"ssh_keep_alive_interval" hcl:"ssh_keep_alive_interval"`
	SSHReadWriteTimeout       *string                  `mapstructure:"ssh_read_write_timeout" cty:"ssh_read_write_timeout" hcl:"ssh_read_write_timeout"`
	SSHRemoteTunnels          []string                 `mapstructure:"ssh_remote_tunnels" cty:"ssh_remote_tunnels" hcl:"ssh_remote_tunnels"`
	SSHLocalTunnels           []string                 `mapstructure:"ssh_local_tunnels" cty:"ssh_local_tunnels" hcl:"ssh_local_tunnels"`
	SSHPublicKey              []byte                   `mapstructure:"ssh_public_key" undocumented:"true" cty:"ssh_public_key" hcl:"ssh_public_key"`
	SSHPrivateKey             []byte                   `mapstructure:"ssh_private_key" undocumented:"true" cty:"ssh_private_key" hcl:"ssh_private_key"`
	WinRMUser                 *string                  `mapstructure:"winrm_username" cty:"winrm_username" hcl:"winrm_username"`
	WinRMPassword             *string                  `mapstructure:"winrm_password" cty:"winrm_password" hcl:"winrm_password"`
	WinRMHost                 *string                  `mapstructure:"winrm_host" cty:"winrm_host" hcl:"winrm_host"`
	WinRMNoProxy              *bool                    `mapstructure:"winrm_no_proxy" cty:"winrm_no_proxy" hcl:"winrm_no_proxy"`
	WinRMPort                 *int                     `mapstructure:"winrm_port" cty:"winrm_port" hcl:"winrm_port"`
	WinRMTimeout              *string                  `mapstructure:"winrm_timeout" cty:"winrm_timeout" hcl:"winrm_timeout"`
	WinRMUseSSL               *bool                    `mapstructure:"winrm_use_ssl" cty:"winrm_use_ssl" hcl:"winrm_use_ssl"`
	WinRMInsecure             *bool                    `mapstructure:"winrm_insecure" cty:"winrm_insecure" hcl:"winrm_insecure"`
	WinRMUseNTLM              *bool                    `mapstructure:"winrm_use_ntlm" cty:"winrm_use_ntlm" hcl:"winrm_use_ntlm"`
	ResourceGroupId           *string                  `mapstructure:"resource_group_id" required:"false" cty:"resource_group_id" hcl:"resource_group_id"`
	ComputerPoolId            *string                  `mapstructure:"computer_pool_id" required:"false" cty:"computer_pool_id" hcl:"computer_pool_id"`
	DesktopName               *string                  `mapstructure:"desktop_name" required:"false" cty:"desktop_name" hcl:"desktop_name"`
	DesktopNameSuffix         *bool                    `mapstructure:"desktop_name_suffix" required:"false" cty:"desktop_name_suffix" hcl:"desktop_name_suffix"`
	Hostname                  *string                  `mapstructure:"hostname" required:"false" cty:"hostname" hcl:"hostname"`
	DesktopIp                 *string                  `mapstructure:"desktop_ip" required:"false" cty:"desktop_ip" hcl:"desktop_ip"`
	VolumeEncryptionEnabled   *bool                    `mapstructure:"volume_encryption_enabled" required:"false" cty:"volume_encryption_enabled" hcl:"volume_encryption_enabled"`
	VolumeEncryptionKey       *string                  `mapstructure:"volume_encryption_key" required:"false" cty:"volume_encryption_key" hcl:"volume_encryption_key"`
	EndUser                   *FlatEdsUser             `mapstructure:"end_user" required:"false" cty:"end_user" hcl:"end_user"`
	OfficeSite                *FlatEdsOfficeSite       `mapstructure:"office_site" required:"false" cty:"office_site" hcl:"office_site"`
	ComputerTemplate          *FlatEdsComputerTemplate `mapstructure:"computer_template" required:"false" cty:"computer_template" hcl:"computer_template"`
	PolicyGroup               *FlatEdsPolicyGroup      `mapstructure:"policy_group" required:"false" cty:"policy_group" hcl:"policy_group"`
	UserCommands              []FlatEdsUserCommand     `mapstructure:"user_commands" required:"false" cty:"user_commands" hcl:"user_commands"`
	Artifact                  *FlatEdsArtifact         `mapstructure:"artifact" required:"true" cty:"artifact" hcl:"artifact"`
}

// FlatMapstructure returns a new FlatRunConfig.
// FlatRunConfig is an auto-generated flat version of RunConfig.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*RunConfig) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatRunConfig)
}

// HCL2Spec returns the hcl spec of a RunConfig.
// This spec is used by HCL to read the fields of RunConfig.
// The decoded values from this spec will then be applied to a FlatRunConfig.
func (*FlatRunConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"communicator":                 &hcldec.AttrSpec{Name: "communicator", Type: cty.String, Required: false},
		"pause_before_connecting":      &hcldec.AttrSpec{Name: "pause_before_connecting", Type: cty.String, Required: false},
		"ssh_host":                     &hcldec.AttrSpec{Name: "ssh_host", Type: cty.String, Required: false},
		"ssh_port":                     &hcldec.AttrSpec{Name: "ssh_port", Type: cty.Number, Required: false},
		"ssh_username":                 &hcldec.AttrSpec{Name: "ssh_username", Type: cty.String, Required: false},
		"ssh_password":                 &hcldec.AttrSpec{Name: "ssh_password", Type: cty.String, Required: false},
		"ssh_keypair_name":             &hcldec.AttrSpec{Name: "ssh_keypair_name", Type: cty.String, Required: false},
		"temporary_key_pair_name":      &hcldec.AttrSpec{Name: "temporary_key_pair_name", Type: cty.String, Required: false},
		"temporary_key_pair_type":      &hcldec.AttrSpec{Name: "temporary_key_pair_type", Type: cty.String, Required: false},
		"temporary_key_pair_bits":      &hcldec.AttrSpec{Name: "temporary_key_pair_bits", Type: cty.Number, Required: false},
		"ssh_ciphers":                  &hcldec.AttrSpec{Name: "ssh_ciphers", Type: cty.List(cty.String), Required: false},
		"ssh_clear_authorized_keys":    &hcldec.AttrSpec{Name: "ssh_clear_authorized_keys", Type: cty.Bool, Required: false},
		"ssh_key_exchange_algorithms":  &hcldec.AttrSpec{Name: "ssh_key_exchange_algorithms", Type: cty.List(cty.String), Required: false},
		"ssh_private_key_file":         &hcldec.AttrSpec{Name: "ssh_private_key_file", Type: cty.String, Required: false},
		"ssh_certificate_file":         &hcldec.AttrSpec{Name: "ssh_certificate_file", Type: cty.String, Required: false},
		"ssh_pty":                      &hcldec.AttrSpec{Name: "ssh_pty", Type: cty.Bool, Required: false},
		"ssh_timeout":                  &hcldec.AttrSpec{Name: "ssh_timeout", Type: cty.String, Required: false},
		"ssh_wait_timeout":             &hcldec.AttrSpec{Name: "ssh_wait_timeout", Type: cty.String, Required: false},
		"ssh_agent_auth":               &hcldec.AttrSpec{Name: "ssh_agent_auth", Type: cty.Bool, Required: false},
		"ssh_disable_agent_forwarding": &hcldec.AttrSpec{Name: "ssh_disable_agent_forwarding", Type: cty.Bool, Required: false},
		"ssh_handshake_attempts":       &hcldec.AttrSpec{Name: "ssh_handshake_attempts", Type: cty.Number, Required: false},
		"ssh_bastion_host":             &hcldec.AttrSpec{Name: "ssh_bastion_host", Type: cty.String, Required: false},
		"ssh_bastion_port":             &hcldec.AttrSpec{Name: "ssh_bastion_port", Type: cty.Number, Required: false},
		"ssh_bastion_agent_auth":       &hcldec.AttrSpec{Name: "ssh_bastion_agent_auth", Type: cty.Bool, Required: false},
		"ssh_bastion_username":         &hcldec.AttrSpec{Name: "ssh_bastion_username", Type: cty.String, Required: false},
		"ssh_bastion_password":         &hcldec.AttrSpec{Name: "ssh_bastion_password", Type: cty.String, Required: false},
		"ssh_bastion_interactive":      &hcldec.AttrSpec{Name: "ssh_bastion_interactive", Type: cty.Bool, Required: false},
		"ssh_bastion_private_key_file": &hcldec.AttrSpec{Name: "ssh_bastion_private_key_file", Type: cty.String, Required: false},
		"ssh_bastion_certificate_file": &hcldec.AttrSpec{Name: "ssh_bastion_certificate_file", Type: cty.String, Required: false},
		"ssh_file_transfer_method":     &hcldec.AttrSpec{Name: "ssh_file_transfer_method", Type: cty.String, Required: false},
		"ssh_proxy_host":               &hcldec.AttrSpec{Name: "ssh_proxy_host", Type: cty.String, Required: false},
		"ssh_proxy_port":               &hcldec.AttrSpec{Name: "ssh_proxy_port", Type: cty.Number, Required: false},
		"ssh_proxy_username":           &hcldec.AttrSpec{Name: "ssh_proxy_username", Type: cty.String, Required: false},
		"ssh_proxy_password":           &hcldec.AttrSpec{Name: "ssh_proxy_password", Type: cty.String, Required: false},
		"ssh_keep_alive_interval":      &hcldec.AttrSpec{Name: "ssh_keep_alive_interval", Type: cty.String, Required: false},
		"ssh_read_write_timeout":       &hcldec.AttrSpec{Name: "ssh_read_write_timeout", Type: cty.String, Required: false},
		"ssh_remote_tunnels":           &hcldec.AttrSpec{Name: "ssh_remote_tunnels", Type: cty.List(cty.String), Required: false},
		"ssh_local_tunnels":            &hcldec.AttrSpec{Name: "ssh_local_tunnels", Type: cty.List(cty.String), Required: false},
		"ssh_public_key":               &hcldec.AttrSpec{Name: "ssh_public_key", Type: cty.List(cty.Number), Required: false},
		"ssh_private_key":              &hcldec.AttrSpec{Name: "ssh_private_key", Type: cty.List(cty.Number), Required: false},
		"winrm_username":               &hcldec.AttrSpec{Name: "winrm_username", Type: cty.String, Required: false},
		"winrm_password":               &hcldec.AttrSpec{Name: "winrm_password", Type: cty.String, Required: false},
		"winrm_host":                   &hcldec.AttrSpec{Name: "winrm_host", Type: cty.String, Required: false},
		"winrm_no_proxy":               &hcldec.AttrSpec{Name: "winrm_no_proxy", Type: cty.Bool, Required: false},
		"winrm_port":                   &hcldec.AttrSpec{Name: "winrm_port", Type: cty.Number, Required: false},
		"winrm_timeout":                &hcldec.AttrSpec{Name: "winrm_timeout", Type: cty.String, Required: false},
		"winrm_use_ssl":                &hcldec.AttrSpec{Name: "winrm_use_ssl", Type: cty.Bool, Required: false},
		"winrm_insecure":               &hcldec.AttrSpec{Name: "winrm_insecure", Type: cty.Bool, Required: false},
		"winrm_use_ntlm":               &hcldec.AttrSpec{Name: "winrm_use_ntlm", Type: cty.Bool, Required: false},
		"resource_group_id":            &hcldec.AttrSpec{Name: "resource_group_id", Type: cty.String, Required: false},
		"computer_pool_id":             &hcldec.AttrSpec{Name: "computer_pool_id", Type: cty.String, Required: false},
		"desktop_name":                 &hcldec.AttrSpec{Name: "desktop_name", Type: cty.String, Required: false},
		"desktop_name_suffix":          &hcldec.AttrSpec{Name: "desktop_name_suffix", Type: cty.Bool, Required: false},
		"hostname":                     &hcldec.AttrSpec{Name: "hostname", Type: cty.String, Required: false},
		"desktop_ip":                   &hcldec.AttrSpec{Name: "desktop_ip", Type: cty.String, Required: false},
		"volume_encryption_enabled":    &hcldec.AttrSpec{Name: "volume_encryption_enabled", Type: cty.Bool, Required: false},
		"volume_encryption_key":        &hcldec.AttrSpec{Name: "volume_encryption_key", Type: cty.String, Required: false},
		"end_user":                     &hcldec.BlockSpec{TypeName: "end_user", Nested: hcldec.ObjectSpec((*FlatEdsUser)(nil).HCL2Spec())},
		"office_site":                  &hcldec.BlockSpec{TypeName: "office_site", Nested: hcldec.ObjectSpec((*FlatEdsOfficeSite)(nil).HCL2Spec())},
		"computer_template":            &hcldec.BlockSpec{TypeName: "computer_template", Nested: hcldec.ObjectSpec((*FlatEdsComputerTemplate)(nil).HCL2Spec())},
		"policy_group":                 &hcldec.BlockSpec{TypeName: "policy_group", Nested: hcldec.ObjectSpec((*FlatEdsPolicyGroup)(nil).HCL2Spec())},
		"user_commands":                &hcldec.BlockListSpec{TypeName: "user_commands", Nested: hcldec.ObjectSpec((*FlatEdsUserCommand)(nil).HCL2Spec())},
		"artifact":                     &hcldec.BlockSpec{TypeName: "artifact", Nested: hcldec.ObjectSpec((*FlatEdsArtifact)(nil).HCL2Spec())},
	}
	return s
}
