// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package ecsimage

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatConfig is an auto-generated flat version of Config.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatConfig struct {
	PackerBuildName               *string           `mapstructure:"packer_build_name" cty:"packer_build_name" hcl:"packer_build_name"`
	PackerBuilderType             *string           `mapstructure:"packer_builder_type" cty:"packer_builder_type" hcl:"packer_builder_type"`
	PackerCoreVersion             *string           `mapstructure:"packer_core_version" cty:"packer_core_version" hcl:"packer_core_version"`
	PackerDebug                   *bool             `mapstructure:"packer_debug" cty:"packer_debug" hcl:"packer_debug"`
	PackerForce                   *bool             `mapstructure:"packer_force" cty:"packer_force" hcl:"packer_force"`
	PackerOnError                 *string           `mapstructure:"packer_on_error" cty:"packer_on_error" hcl:"packer_on_error"`
	PackerUserVars                map[string]string `mapstructure:"packer_user_variables" cty:"packer_user_variables" hcl:"packer_user_variables"`
	PackerSensitiveVars           []string          `mapstructure:"packer_sensitive_variables" cty:"packer_sensitive_variables" hcl:"packer_sensitive_variables"`
	AlicloudAccessKey             *string           `mapstructure:"access_key" required:"true" cty:"access_key" hcl:"access_key"`
	AlicloudSecretKey             *string           `mapstructure:"secret_key" required:"true" cty:"secret_key" hcl:"secret_key"`
	AlicloudRegion                *string           `mapstructure:"region" required:"true" cty:"region" hcl:"region"`
	AlicloudRamRole               *string           `mapstructure:"ram_role_name" required:"true" cty:"ram_role_name" hcl:"ram_role_name"`
	AlicloudRamRoleArn            *string           `mapstructure:"ram_role_arn" required:"true" cty:"ram_role_arn" hcl:"ram_role_arn"`
	AlicloudRamSessionName        *string           `mapstructure:"ram_session_name" required:"true" cty:"ram_session_name" hcl:"ram_session_name"`
	AlicloudSkipValidation        *bool             `mapstructure:"skip_region_validation" required:"false" cty:"skip_region_validation" hcl:"skip_region_validation"`
	AlicloudSkipImageValidation   *bool             `mapstructure:"skip_image_validation" required:"false" cty:"skip_image_validation" hcl:"skip_image_validation"`
	AlicloudProfile               *string           `mapstructure:"profile" required:"false" cty:"profile" hcl:"profile"`
	AlicloudSharedCredentialsFile *string           `mapstructure:"shared_credentials_file" required:"false" cty:"shared_credentials_file" hcl:"shared_credentials_file"`
	SecurityToken                 *string           `mapstructure:"security_token" required:"false" cty:"security_token" hcl:"security_token"`
	CustomEndpointEcs             *string           `mapstructure:"custom_endpoint_ecs" required:"false" cty:"custom_endpoint_ecs" hcl:"custom_endpoint_ecs"`
	ImageId                       *string           `mapstructure:"image_id" cty:"image_id" hcl:"image_id"`
	ImageName                     *string           `mapstructure:"image_name" cty:"image_name" hcl:"image_name"`
	ImageFamily                   *string           `mapstructure:"image_family" cty:"image_family" hcl:"image_family"`
	IsPublic                      *bool             `mapstructure:"is_public" cty:"is_public" hcl:"is_public"`
	Source                        *string           `mapstructure:"source" cty:"source" hcl:"source"`
	OwnerId                       *int64            `mapstructure:"owner_id" cty:"owner_id" hcl:"owner_id"`
	OSType                        *string           `mapstructure:"os_type" cty:"os_type" hcl:"os_type"`
	Architecture                  *string           `mapstructure:"architecture" cty:"architecture" hcl:"architecture"`
	Tags                          []FlatImageTag    `mapstructure:"tags" cty:"tags" hcl:"tags"`
	Usage                         *string           `mapstructure:"usage" cty:"usage" hcl:"usage"`
}

// FlatMapstructure returns a new FlatConfig.
// FlatConfig is an auto-generated flat version of Config.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Config) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatConfig)
}

// HCL2Spec returns the hcl spec of a Config.
// This spec is used by HCL to read the fields of Config.
// The decoded values from this spec will then be applied to a FlatConfig.
func (*FlatConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"packer_build_name":          &hcldec.AttrSpec{Name: "packer_build_name", Type: cty.String, Required: false},
		"packer_builder_type":        &hcldec.AttrSpec{Name: "packer_builder_type", Type: cty.String, Required: false},
		"packer_core_version":        &hcldec.AttrSpec{Name: "packer_core_version", Type: cty.String, Required: false},
		"packer_debug":               &hcldec.AttrSpec{Name: "packer_debug", Type: cty.Bool, Required: false},
		"packer_force":               &hcldec.AttrSpec{Name: "packer_force", Type: cty.Bool, Required: false},
		"packer_on_error":            &hcldec.AttrSpec{Name: "packer_on_error", Type: cty.String, Required: false},
		"packer_user_variables":      &hcldec.AttrSpec{Name: "packer_user_variables", Type: cty.Map(cty.String), Required: false},
		"packer_sensitive_variables": &hcldec.AttrSpec{Name: "packer_sensitive_variables", Type: cty.List(cty.String), Required: false},
		"access_key":                 &hcldec.AttrSpec{Name: "access_key", Type: cty.String, Required: false},
		"secret_key":                 &hcldec.AttrSpec{Name: "secret_key", Type: cty.String, Required: false},
		"region":                     &hcldec.AttrSpec{Name: "region", Type: cty.String, Required: false},
		"ram_role_name":              &hcldec.AttrSpec{Name: "ram_role_name", Type: cty.String, Required: false},
		"ram_role_arn":               &hcldec.AttrSpec{Name: "ram_role_arn", Type: cty.String, Required: false},
		"ram_session_name":           &hcldec.AttrSpec{Name: "ram_session_name", Type: cty.String, Required: false},
		"skip_region_validation":     &hcldec.AttrSpec{Name: "skip_region_validation", Type: cty.Bool, Required: false},
		"skip_image_validation":      &hcldec.AttrSpec{Name: "skip_image_validation", Type: cty.Bool, Required: false},
		"profile":                    &hcldec.AttrSpec{Name: "profile", Type: cty.String, Required: false},
		"shared_credentials_file":    &hcldec.AttrSpec{Name: "shared_credentials_file", Type: cty.String, Required: false},
		"security_token":             &hcldec.AttrSpec{Name: "security_token", Type: cty.String, Required: false},
		"custom_endpoint_ecs":        &hcldec.AttrSpec{Name: "custom_endpoint_ecs", Type: cty.String, Required: false},
		"image_id":                   &hcldec.AttrSpec{Name: "image_id", Type: cty.String, Required: false},
		"image_name":                 &hcldec.AttrSpec{Name: "image_name", Type: cty.String, Required: false},
		"image_family":               &hcldec.AttrSpec{Name: "image_family", Type: cty.String, Required: false},
		"is_public":                  &hcldec.AttrSpec{Name: "is_public", Type: cty.Bool, Required: false},
		"source":                     &hcldec.AttrSpec{Name: "source", Type: cty.String, Required: false},
		"owner_id":                   &hcldec.AttrSpec{Name: "owner_id", Type: cty.Number, Required: false},
		"os_type":                    &hcldec.AttrSpec{Name: "os_type", Type: cty.String, Required: false},
		"architecture":               &hcldec.AttrSpec{Name: "architecture", Type: cty.String, Required: false},
		"tags":                       &hcldec.BlockListSpec{TypeName: "tags", Nested: hcldec.ObjectSpec((*FlatImageTag)(nil).HCL2Spec())},
		"usage":                      &hcldec.AttrSpec{Name: "usage", Type: cty.String, Required: false},
	}
	return s
}

// FlatDatasourceOutput is an auto-generated flat version of DatasourceOutput.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatDatasourceOutput struct {
	Image *FlatImage `mapstructure:"image" cty:"image" hcl:"image"`
}

// FlatMapstructure returns a new FlatDatasourceOutput.
// FlatDatasourceOutput is an auto-generated flat version of DatasourceOutput.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*DatasourceOutput) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatDatasourceOutput)
}

// HCL2Spec returns the hcl spec of a DatasourceOutput.
// This spec is used by HCL to read the fields of DatasourceOutput.
// The decoded values from this spec will then be applied to a FlatDatasourceOutput.
func (*FlatDatasourceOutput) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"image": &hcldec.BlockSpec{TypeName: "image", Nested: hcldec.ObjectSpec((*FlatImage)(nil).HCL2Spec())},
	}
	return s
}

// FlatImage is an auto-generated flat version of Image.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatImage struct {
	ImageId      *string        `mapstructure:"image_id" cty:"image_id" hcl:"image_id"`
	ImageName    *string        `mapstructure:"image_name" cty:"image_name" hcl:"image_name"`
	ImageFamily  *string        `mapstructure:"image_family" cty:"image_family" hcl:"image_family"`
	IsPublic     *bool          `mapstructure:"is_public" cty:"is_public" hcl:"is_public"`
	Source       *string        `mapstructure:"source" cty:"source" hcl:"source"`
	OwnerId      *int64         `mapstructure:"owner_id" cty:"owner_id" hcl:"owner_id"`
	OSType       *string        `mapstructure:"os_type" cty:"os_type" hcl:"os_type"`
	Architecture *string        `mapstructure:"architecture" cty:"architecture" hcl:"architecture"`
	Tags         []FlatImageTag `mapstructure:"tags" cty:"tags" hcl:"tags"`
	Usage        *string        `mapstructure:"usage" cty:"usage" hcl:"usage"`
}

// FlatMapstructure returns a new FlatImage.
// FlatImage is an auto-generated flat version of Image.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Image) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatImage)
}

// HCL2Spec returns the hcl spec of a Image.
// This spec is used by HCL to read the fields of Image.
// The decoded values from this spec will then be applied to a FlatImage.
func (*FlatImage) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"image_id":     &hcldec.AttrSpec{Name: "image_id", Type: cty.String, Required: false},
		"image_name":   &hcldec.AttrSpec{Name: "image_name", Type: cty.String, Required: false},
		"image_family": &hcldec.AttrSpec{Name: "image_family", Type: cty.String, Required: false},
		"is_public":    &hcldec.AttrSpec{Name: "is_public", Type: cty.Bool, Required: false},
		"source":       &hcldec.AttrSpec{Name: "source", Type: cty.String, Required: false},
		"owner_id":     &hcldec.AttrSpec{Name: "owner_id", Type: cty.Number, Required: false},
		"os_type":      &hcldec.AttrSpec{Name: "os_type", Type: cty.String, Required: false},
		"architecture": &hcldec.AttrSpec{Name: "architecture", Type: cty.String, Required: false},
		"tags":         &hcldec.BlockListSpec{TypeName: "tags", Nested: hcldec.ObjectSpec((*FlatImageTag)(nil).HCL2Spec())},
		"usage":        &hcldec.AttrSpec{Name: "usage", Type: cty.String, Required: false},
	}
	return s
}

// FlatImageTag is an auto-generated flat version of ImageTag.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatImageTag struct {
	TagKey   *string `mapstructure:"key" cty:"key" hcl:"key"`
	TagValue *string `mapstructure:"value" cty:"value" hcl:"value"`
}

// FlatMapstructure returns a new FlatImageTag.
// FlatImageTag is an auto-generated flat version of ImageTag.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*ImageTag) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatImageTag)
}

// HCL2Spec returns the hcl spec of a ImageTag.
// This spec is used by HCL to read the fields of ImageTag.
// The decoded values from this spec will then be applied to a FlatImageTag.
func (*FlatImageTag) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"key":   &hcldec.AttrSpec{Name: "key", Type: cty.String, Required: false},
		"value": &hcldec.AttrSpec{Name: "value", Type: cty.String, Required: false},
	}
	return s
}
